/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.praktikumpbo.crudkontak.Frame;

import controllers.ControllerKontak;
import interfaces.InterfaceKontak;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import models.Kontak;

/**
 *
 * @author Putri
 */
public class FrameKontak extends javax.swing.JFrame {
    
    List<Kontak> record = new ArrayList<Kontak>();
    InterfaceKontak serviceKontak;
    int row;
    /**
     * Creates new form FrameKontak
     */
    public FrameKontak() {
        initComponents();
         NamaValidasiLabel.setVisible(false);
         AlamatValidasiLabel.setVisible(false);
         AlamatValidasiLabel.setVisible(false);
        serviceKontak = new ControllerKontak();
        TablePhoneBook.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            row = TablePhoneBook.getSelectedRow();
            if(row != -1){
                fillField();
            }
        });

        this.refreshData();
    }
    
    //Method Load Data
    void loadData() {
        
        try {
            record = serviceKontak.getAll();
        } catch(SQLException exception){
            Logger.getLogger(FrameKontak.class.getName()).log(Level.SEVERE, null, exception);
        }
    }
    
    //Method Isi Tabel
    void fillTable() {
        
        Object data[][] = new Object[record.size()][4];
        int i = 0;
        for (Kontak k:record) {
            data[i][0] = k.getId();
            data[i][1] = k.getNama();
            data[i][2] = k.getTelepon();
            data[i][3] = k.getAlamat();
            i++;
        }
        String kolom[] = {"ID", "Nama", "Telepon", "Alamat"};
        TablePhoneBook.setModel(new DefaultTableModel(data, kolom));
        scrollPaneTable.setViewportView(TablePhoneBook);
    }
    
    //Method Isi Field
    void fillField() {
        
        Kontak kontak = record.get(row);
        IdLabel.setText(String.valueOf(kontak.getId()));
        NamaField.setText(kontak.getNama());
        TeleponField.setText(kontak.getTelepon());
        TextAlamat.setText(kontak.getAlamat());
    }
    
    //Method Clean/Bersihkan Field
    void cleanField() {
        
        NamaField.setText("");
        TeleponField.setText("");
        TextAlamat.setText("");
        IdLabel.setText(null);
    }
    
    //Method Refresh Data
    private void refreshData() {
        
        cleanField();
        loadData();
        fillTable();
    }
    
    void validasiInput(Kontak k) {
        if (!NamaField.getText().equals("")) {
            NamaValidasiLabel.setText("Nama belum diisi");
            NamaValidasiLabel.setVisible(true);
        } else {
            k.setTelepon(NamaField.getText());
            NamaValidasiLabel.setVisible(false);
        }
        if (TeleponField.getText().equals("")) {
            TeleponValidasiLabel.setText("Nomor belum diisi");
            TeleponValidasiLabel.setVisible(true);
        } else if (!TeleponField.getText().matches("[0-9]*")) {
            TeleponValidasiLabel.setText("Nomor harus berisi angka");
            TeleponValidasiLabel.setVisible(true);
        } else if (TeleponField.getText().length() <5){
            TeleponValidasiLabel.setText("Nomor minimal berisi 5 angka");
           TeleponValidasiLabel.setVisible(true);
        } else if (TeleponField.getText().length() > 13) {
            TeleponValidasiLabel.setText("Nomor maksimal berisi 13 angka");
            TeleponValidasiLabel.setVisible(true);
        }

        if (TextAlamat.getText().equals("")) {
            AlamatValidasiLabel.setText("Alamat belum diisi");
            AlamatValidasiLabel.setVisible(true);
        } else {
            k.setAlamat(TextAlamat.getText());
            AlamatValidasiLabel.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelTelepon = new javax.swing.JLabel();
        LabelAlamat = new javax.swing.JLabel();
        NamaField = new javax.swing.JTextField();
        TeleponField = new javax.swing.JTextField();
        scrollPaneTable = new javax.swing.JScrollPane();
        TablePhoneBook = new javax.swing.JTable();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAlamat = new javax.swing.JTextArea();
        IdLabel = new javax.swing.JLabel();
        NamaValidasiLabel = new javax.swing.JLabel();
        TeleponValidasiLabel = new javax.swing.JLabel();
        AlamatValidasiLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CRUD Buku Kontak");

        LabelNama.setText("Nama");

        LabelTelepon.setText("Telepon");

        LabelAlamat.setText("Alamat");

        NamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaFieldActionPerformed(evt);
            }
        });

        TeleponField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeleponFieldActionPerformed(evt);
            }
        });

        TablePhoneBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Telepon", "Alamat"
            }
        ));
        TablePhoneBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePhoneBookMouseClicked(evt);
            }
        });
        scrollPaneTable.setViewportView(TablePhoneBook);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        TextAlamat.setColumns(20);
        TextAlamat.setRows(5);
        jScrollPane2.setViewportView(TextAlamat);

        IdLabel.setText("Id");

        NamaValidasiLabel.setForeground(new java.awt.Color(255, 0, 51));
        NamaValidasiLabel.setText("jLabel2");

        TeleponValidasiLabel.setForeground(new java.awt.Color(255, 0, 51));
        TeleponValidasiLabel.setText("jLabel3");

        AlamatValidasiLabel.setForeground(new java.awt.Color(255, 0, 51));
        AlamatValidasiLabel.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddButton)
                        .addGap(59, 59, 59)
                        .addComponent(UpdateButton)
                        .addGap(55, 55, 55)
                        .addComponent(DeleteButton)
                        .addGap(56, 56, 56)
                        .addComponent(RefreshButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelAlamat)
                            .addComponent(LabelNama)
                            .addComponent(LabelTelepon))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaValidasiLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NamaField, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                                .addComponent(TeleponField)
                                .addComponent(jScrollPane2))
                            .addComponent(TeleponValidasiLabel)
                            .addComponent(AlamatValidasiLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(scrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(IdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama)
                    .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaValidasiLabel)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeleponField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTelepon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TeleponValidasiLabel)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAlamat))
                .addGap(8, 8, 8)
                .addComponent(AlamatValidasiLabel)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton)
                    .addComponent(RefreshButton))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaFieldActionPerformed
        // TODO add your handling code here:
                                            
    }//GEN-LAST:event_NamaFieldActionPerformed

    private void TeleponFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeleponFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeleponFieldActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        try {
            Kontak kontak = new Kontak();
            validasiInput(kontak); 
            kontak.setNama(NamaField.getText());
            kontak.setTelepon(TeleponField.getText());
            kontak.setAlamat(TextAlamat.getText());
            serviceKontak.insert(kontak);
            this.refreshData();
            JOptionPane.showMessageDialog(this, "Data Tersimpan");
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Data Gagal Tersimpan");
            Logger.getLogger(FrameKontak.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        try {
            String id = IdLabel.getText();
            serviceKontak.delete(Integer.parseInt(id));
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
            Logger.getLogger(FrameKontak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        try {
            Kontak kontak = new Kontak();
            validasiInput(kontak);
            kontak.setNama(NamaField.getText());
            kontak.setTelepon(TeleponField.getText());
            kontak.setAlamat(TextAlamat.getText());
            serviceKontak.update(kontak);
            this.refreshData();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Data Gagal Diubah");
            Logger.getLogger(FrameKontak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        this.refreshData();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void TablePhoneBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePhoneBookMouseClicked
        // TODO add your handling code here:
        TablePhoneBook.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            row = TablePhoneBook.getSelectedRow();
            if (row != -1){
                fillField();
            }
        });
    }//GEN-LAST:event_TablePhoneBookMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameKontak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AlamatValidasiLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelTelepon;
    private javax.swing.JTextField NamaField;
    private javax.swing.JLabel NamaValidasiLabel;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JTable TablePhoneBook;
    private javax.swing.JTextField TeleponField;
    private javax.swing.JLabel TeleponValidasiLabel;
    private javax.swing.JTextArea TextAlamat;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane scrollPaneTable;
    // End of variables declaration//GEN-END:variables

    
    
    private static class jScrollPanel {

        public jScrollPanel() {
        }
    }
}
